name: learn_offline
description: Offline Learning App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Firebase
  firebase_core: 2.24.2
  firebase_auth: 4.15.3
  google_sign_in: 6.2.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Networking
  http: ^1.2.0
  dio: ^5.4.0
  html: ^0.15.4
  
  # File Management
  path: ^1.8.3
  image_picker: ^1.0.7
  
  # Utilities
  permission_handler: ^11.3.0
  intl: ^0.19.0
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  # Media Playback & Documents
  video_player: ^2.8.2
  chewie: ^1.7.0
  syncfusion_flutter_pdfviewer: ^32.1.23
  youtube_player_flutter: ^9.1.3
  youtube_explode_dart: ^3.0.5
  dio_smart_retry: ^7.0.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/educache_logo.png
    - assets/images/
    - assets/images/onboarding1.jpg
    - assets/images/onboarding2.jpg
    - assets/images/onboarding3.jpg
    - assets/images/architecture.jpg
    - assets/images/philosophy.jpg
    - assets/images/finance.jpg
    - assets/images/writing.jpg
    - assets/images/sustainable.jpg
    - assets/images/art.jpg
    - assets/images/avatar.jpg
    - assets/images/google_logo.png